const searches = [
    { "search": "why do i have to pee so much"},
    { "search": "when i jump i hear water" }, 
    { "search": "why is my goldfish turning black" },
    { "search": "what is the answer to life the universe everything" }, 
    { "search": "what if google was a guy part 2" },
    { "search": "what does it mean when you dream about snakes" }, 
    { "search": "what does it mean when your poop floats" },
    { "search": "what are these strawberries doing on google" },  
    { "search": "how come cupcake is not considered a mineral" },
    { "search": "how come alicia keys lyrics" }, 
    { "search": "help i'm a prisoner in the library" },
    { "search": "why isnt 11 pronounced onety one" },
    { "search": "help i'm a pastor's wife" },
    { "search": "do you ever look at yourself in the mirror and think what wattage" }, 
    { "search": "do you ever look at the moon joe dirt" },
    { "search": "don't you hate it when a sentence doesn't end the way it octopus" }, 
    { "search": "don't you hate it when a llama named carl" },
    { "search": "don't you hate it when a sentence" }, 
    { "search": "don't you hate it when a chinchilla eats the universe" },
    { "search": "don't you hate it when a sentence doesn't" }, 
    { "search": "is it normal to eat period blood" },
    { "search": "is it normal to have green poop" }, 
    { "search": "is it normal to be sexually attracted to numbers" },
    { "search": "is it possible to live forever" }, 
    { "search": "my girlfriend is the president" },
    { "search": "never put a sock in the toaster" }, 
    { "search": "never put a genie on a budget" },
    { "search": "never put a qtip in your ear" }, 
    { "search": "sometimes i like to pretend i'm a carrot" },
    { "search": "sometimes i like to pretend i'm a meatball" }, 
    { "search": "sometimes i like to cover myself in vaseline" },
    { "search": "do men have hot flashes" }, 
    { "search": "do men have one less rib" },
    { "search": "dinosaurs were made up by the CIA to discourage time travel lyrics" }, 
    { "search": "did you have a brain tumor for breakfast" },
    { "search": "is it impossible to lick your elbow" }, 
    { "search": "is it bad if your poop floats" },
    { "search": "is it bad if you don't dream" }, 
    { "search": "if i ate myself would i double in size" },
    { "search": "i ate a big red candle meaning" }, 
    { "search": "how do i quit my job" },
    { "search": "how do i quit smoking" }, 
    { "search": "how do i qualify for mortgage" },
    { "search": "what would happen if the sun exploded" }, 
    { "search": "what would happen if photosynthesis on earth stopped" },
    { "search": "what would happen if mitosis were uncontrolled" }, 
    { "search": "how can i keep from singing" },
    { "search": "should i stay or should i go lyrics" }, 
    { "search": "should i go to law school" },
    { "search": "why can't an open universe have a center" }, 
    { "search": "what is planking" },
    { "search": "why are flamingos pink" }, 
    { "search": "why are yawns contagious"  },
    { "search": "why are people planking" }, 
    { "search": "why do dogs eat grass" },
    { "search": "why don't women like nice guys" }, 
    { "search": "do other people exist" },
    { "search": "is it crazy to go to dubai in august"  }, 
    { "search": "is it impossible to sneeze with your eyes open" },
    { "search": "how does facebook make money" }, 
    { "search": "what would a chair look like if you bent your knees the other way" },
    { "search": "what would Dave do" }, 
    { "search": "why are the oceans salty" },
    { "search": "why are the bees dying" }, 
    { "search": "sometimes when i'm alone i use comic sans" },
    { "search": "can i eat my himalayan salt lamp" }, 
    { "search": "could god create another god" },
    { "search": "why aren't there guns in harry potter" }, 
    { "search": "unicorns in the bible" },
    { "search": "what are these strong guys or something" }, 
    { "search": "why are there seasons" },
    { "search": "why is my goldfish swimming upside down" }, 
    { "search": "what if we kissed meme" },
    { "search": "what if we didn't have a moon" }, 
    { "search": "why does dog poop turn white" },
    { "search": "how do you think crtiically" }, 
    { "search": "how does someone get ringworm" },
    { "search": "why are hot dogs red" }, 
    { "search": "why does money need to be laundered" },
    { "search": "who made roblox" }, 
    { "search": "who invented walking" }
]

export default searches;