const affirmations = [
    {"search": "i am successful!"},
    {"search": "i am powerful"},
    {"search": "i am getting better and better every day"},
    {"search": "all i need is within me right now"},
    {"search": "i am an unstoppable force of nature"},
    {"search": "i am a living, breathing example of motivation"},
    {"search": "i am living with abundance"},
    {"search": "i am inspiring people through my work"},
    {"search": "today is a phenomenal day!"},
    {"search": "i am filled with focus!"},
    {"search": "i am not pushed by problems, i am led by my dreams"},
    {"search": "i am independent and self-sufficient"},
    {"search": "i can be whatever i want to be"},
    {"search": "today will be a productive day"},
    {"search": "each and every day, i am getting closer to achieving my goals"},
    {"search": "free yourself from all destructive doubt and fear"},
    {"search": "my soul radiates from the inside and warms the souls of others"},
    {"search": "i finish what matters and let go of what does not"},
    {"search": "what i have done today was the best i was able to do today"},
    {"search": "one small positive thought in the morning can change your whole day"},
    {"search": "i am growing and going at my own pace"},
    {"search": "i am doing the work that works for me"},
    {"search": "i get better every single day!"},
    {"search": "i can get through anything!"},
    {"search": "today i choose to think positive"},
    {"search": "good things are going to come to me"},
    {"search": "i matter."},
    {"search": "it's okay to make mistakes"},
    {"search": "no matter how hard it is, i can do it!"},
    {"search": "with every breath, i feel stronger"},
    {"search": "my success is just around the corner"},
    {"search": "i am in control of my emotions"},
    {"search": "i am becoming the best version of myself"},
    {"search": "my mistakes help me learn and grow"},
    {"search": "there is no one better to be than myself"},
    {"search": "my challenges help me grow"},
    {"search": "it's okay to not know everything."},
    {"search": "i am capable of so much!"},
    {"search": "i believe in myself and my abilities"},
    {"search": "i am open and ready to learn."},
    {"search": "today is going to be an awesome day!"},
    {"search": "i start with a positive mindset."},
    {"search": "i give myself permission to make mistakes."},
    {"search": "i've got this!"},
    {"search": "i'm going to push through!"},
    {"search": "i'm going to take a chance!"},
    {"search": "i am prepared to succeed"},
    {"search": "i'm starting a new chapter today!"},
    {"search": "i am important."}
]

export default affirmations;