const inspirational = [

    { "search":"Life isn't about getting and having, it's about giving and being.","author":"Kevin Kruse"},
    { "search":"Strive not to be a success, but rather to be of value.","author":"Albert Einstein"},
    { "search":"You miss 100% of the shots you don't take.","author":"Wayne Gretzky"},
    { "search":"Every strike brings me closer to the next home run.","author":"Babe Ruth"},
    { "search":"We become what we think about.","author":"Earl Nightingale"},
    { "search":"Either you run the day, or the day runs you.","author":"Jim Rohn"},
    { "search":"Whether you think you can or you think you can't, you're right.","author":"Henry Ford"},
    { "search":"The best revenge is massive success.","author":"Frank Sinatra"},
    { "search":"Life shrinks or expands in proportion to one's courage.","author":"Anais Nin"},
    { "search":"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.","author":"Aristotle"},
    { "search":"The only person you are destined to become is the person you decide to be.","author":"Ralph Waldo Emerson"},
    { "search":"Go confidently in the direction of your dreams. Live the life you have imagined.","author":"Henry David Thoreau"},
    { "search":"Certain things catch your eye, but pursue only those that capture the heart.","author":" Ancient Indian Proverb"},
    { "search":"Believe you can and you're halfway there.","author":"Theodore Roosevelt"},
    { "search":"Everything you've ever wanted is on the other side of fear.","author":"George Addair"},
    { "search":"Teach thy tongue to say, “I do not know,” and thous shalt progress.","author":"Maimonides"},
    { "search":"Start where you are. Use what you have.  Do what you can.","author":"Arthur Ashe"},
    { "search":"Fall seven times and stand up eight.","author":"Japanese Proverb"},
    { "search":"Everything has beauty, but not everyone can see.","author":"Confucius"},
    { "search":"When I let go of what I am, I become what I might be.","author":"Lao Tzu"},
    { "search":"If you're offered a seat on a rocket ship, don't ask what seat! Just get on.","author":"Sheryl Sandberg"},
    { "search":"If the wind will not serve, take to the oars.","author":"Latin Proverb"},
    { "search":"Too many of us are not living our dreams because we are living our fears.","author":"Les Brown"},
    { "search":"If you want to lift yourself up, lift up someone else.","author":"Booker T. Washington"},
    { "search":"I didn't fail the test. I just found 100 ways to do it wrong.","author":"Benjamin Franklin"},
    { "search":"A person who never made a mistake never tried anything new.","author":" Albert Einstein"},
    { "search":"There are no traffic jams along the extra mile.","author":"Roger Staubach"},
    { "search":"It is never too late to be what you might have been.","author":"George Eliot"},
    { "search":"You become what you believe.","author":"Oprah Winfrey"},
    { "search":"I would rather die of passion than of boredom.","author":"Vincent van Gogh"},
    { "search":"Build your own dreams, or someone else will hire you to build theirs.","author":"Farrah Gray"},
    { "search":"Education costs money. But then so does ignorance.","author":"Sir Claus Moser"},
    { "search":"It does not matter how slowly you go as long as you do not stop.","author":"Confucius"},
    { "search":"Remember that not getting what you want is sometimes a wonderful stroke of luck.","author":"Dalai Lama"},
    { "search":"You can't use up creativity. The more you use, the more you have.","author":"Maya Angelou"},
    { "search":"Dream big and dare to fail.","author":"Norman Vaughan"},
    { "search":"Our lives begin to end the day we become silent about things that matter.","author":"Martin Luther King Jr."},
    { "search":"Do what you can, where you are, with what you have.","author":"Teddy Roosevelt"},
    { "search":"If you do what you've always done, you'll get what you've always gotten.","author":"Tony Robbins"},
    { "search":"Dreaming, after all, is a form of planning.","author":"Gloria Steinem"},
    { "search":"You may be disappointed if you fail, but you are doomed if you don't try.","author":"Beverly Sills"},
    { "search":"Remember no one can make you feel inferior without your consent.","author":"Eleanor Roosevelt"},
    { "search":"Life is what we make it, always has been, always will be.","author":"Grandma Moses"},
    { "search":"The question isn't who is going to let me; it's who is going to stop me.","author":"Ayn Rand"},
    { "search":"It's not the years in your life that count. It's the life in your years.","author":"Abraham Lincoln"},
    { "search":"Change your thoughts and you change your world.","author":"Norman Vincent Peale"},
    { "search":"Either write something worth reading or do something worth writing.","author":"Benjamin Franklin"},
    { "search":"Nothing is impossible, the word itself says, “I'm possible!”","author":"–Audrey Hepburn"},
    { "search":"The only way to do great work is to love what you do.","author":"Steve Jobs"},
    { "search":"If you can dream it, you can achieve it.","author":"Zig Ziglar"}
]

export default inspirational;