const random = [
    { "search": "what is the answer to life the universe everything" }, 
    { "search": "what does it mean when you dream about snakes" }, 
    { "search": "is it possible to live forever" }, 
    { "search": "do men have one less rib" },
    { "search": "is it impossible to lick your elbow" }, 
    { "search": "is it bad if you don't dream" }, 
    { "search": "how do i qualify for mortgage" },
    { "search": "what would happen if the sun exploded" }, 
    { "search": "what would happen if photosynthesis on earth stopped" },
    { "search": "what would happen if mitosis were uncontrolled" }, 
    { "search": "why can't an open universe have a center" }, 
    { "search": "why are flamingos pink" }, 
    { "search": "why are yawns contagious"  },
    { "search": "is it impossible to sneeze with your eyes open" },
    { "search": "why are there seasons" },
    { "search": "what if we didn't have a moon" }, 
    { "search": "who invented walking" },
    { "search": "never put a genie on a budget" },
    { "search": "sometimes i like to pretend i'm a meatball" }, 
    { "search": "sometimes i like to cover myself in vaseline" },
    { "search": "don't you hate it when a sentence doesn't" }, 
    { "search": "why isnt 11 pronounced onety one" },
    { "search": "what are these strawberries doing on google" },  
    { "search": "dinosaurs were made up by the CIA to discourage time travel lyrics" }, 
    { "search": "if i ate myself would i double in size" },
    { "search": "how do i quit my job" },
    { "search": "how do i quit smoking" }, 
    { "search": "how can i keep from singing" },
    { "search": "do other people exist" },
    { "search": "how do you change your zodiac sign" }, 
    { "search": "what would happen if i hired two private investigators to follow each other"},
    { "search": "sometimes i like to pretend i'm a carrot" },
    { "search": "my teeth are see through"},
    { "search": "why do all these old bands keep covering glee songs"},
    { "search": "can i eat my himalayan salt lamp"},
    { "search": "how can i become two men that weigh 250 pounds"},
    { "search": "what's a boyfriend and where can i download one"},
    { "search": "people describe the first time they drank gatorade"},
    { "search": "can chuck norris divide by zero"},
    { "search": "am i a vampire"},
    { "search": "my computer is eating my words"},
    { "search": "my computer is haunted"},
    { "search": "The secret ingredient to his wonderful life was crime."},
    { "search": "The ice-cream trucks bring back bad memories for all of us."},
    { "search": "It isn't difficult to do a handstand if you just stand on your hands."},
    { "search": "I hate it when Voldemort uses my shampoo"},
    { "search": "I hate it when the Loch Ness monster asks me for $3.50"},
    { "search": "I have no mouth and I must scream"},
    { "search": "What the heck is a salad?"},

]

export default random;